/**
 * Created by hasen on 2017/6/19.
 */

function goAccessList(state) {
    state.go('app.audit.access');
}


function accessTransform(val) {
    if (val) {
        val = 1;
    } else {
        val = 0;
    }

    return val;
}

var vxAccessJson = {
    "startIndex": 0,
    "pageSize": 25,
    "totalCount": 2991075,
    "resultSize": 50,
    "queryTimeMS": 1497919462476,
    "vXAccessAudits": [
        {
            "id": 863163055,
            "createDate": null,
            "updateDate": null,
            "auditType": 0,
            "accessResult": 1,
            "accessType": "READ",
            "aclEnforcer": "hadoop-acl",
            "clientIP": "172.16.16.151",
            "policyId": -1,
            "repoName": "cluster_hadoop",
            "repoType": 1,
            "serviceType": "hdfs",
            "resultReason": "/spark2-history/application_1496884763607_0003.inprogress",
            "eventTime": "2017-06-20T00:44:14Z",
            "requestUser": "spark",
            "action": "read",
            "resourcePath": "/spark2-history/application_1496884763607_0003.inprogress",
            "resourceType": "path",
            "sequenceNumber": 1394654,
            "eventCount": 1,
            "eventDuration": 0
        },
        {
            "id": 863163053,
            "createDate": null,
            "updateDate": null,
            "auditType": 0,
            "accessResult": 1,
            "accessType": "READ",
            "aclEnforcer": "hadoop-acl",
            "clientIP": "172.16.16.151",
            "policyId": -1,
            "repoName": "cluster_hadoop",
            "repoType": 1,
            "serviceType": "hdfs",
            "resultReason": "/spark2-history/application_1496884763607_0002.inprogress",
            "eventTime": "2017-06-20T00:44:14Z",
            "requestUser": "spark",
            "action": "read",
            "resourcePath": "/spark2-history/application_1496884763607_0002.inprogress",
            "resourceType": "path",
            "sequenceNumber": 1394650,
            "eventCount": 1,
            "eventDuration": 0
        },
        {
            "id": 863163054,
            "createDate": null,
            "updateDate": null,
            "auditType": 0,
            "accessResult": 1,
            "accessType": "READ",
            "aclEnforcer": "hadoop-acl",
            "clientIP": "172.16.16.151",
            "policyId": -1,
            "repoName": "cluster_hadoop",
            "repoType": 1,
            "serviceType": "hdfs",
            "resultReason": "/spark2-history/application_1496884763607_0004.inprogress",
            "eventTime": "2017-06-20T00:44:14Z",
            "requestUser": "spark",
            "action": "read",
            "resourcePath": "/spark2-history/application_1496884763607_0004.inprogress",
            "resourceType": "path",
            "sequenceNumber": 1394652,
            "eventCount": 1,
            "eventDuration": 0
        },
        {
            "id": 863163052,
            "createDate": null,
            "updateDate": null,
            "auditType": 0,
            "accessResult": 1,
            "accessType": "READ_EXECUTE",
            "aclEnforcer": "hadoop-acl",
            "clientIP": "172.16.16.151",
            "policyId": -1,
            "repoName": "cluster_hadoop",
            "repoType": 1,
            "serviceType": "hdfs",
            "resultReason": "/spark2-history",
            "eventTime": "2017-06-20T00:44:14Z",
            "requestUser": "spark",
            "action": "read",
            "resourcePath": "/spark2-history",
            "resourceType": "path",
            "sequenceNumber": 1394648,
            "eventCount": 1,
            "eventDuration": 0
        },
        {
            "id": 863163050,
            "createDate": null,
            "updateDate": null,
            "auditType": 0,
            "accessResult": 1,
            "accessType": "WRITE",
            "aclEnforcer": "hadoop-acl",
            "clientIP": "172.16.16.151",
            "policyId": -1,
            "repoName": "cluster_hadoop",
            "repoType": 1,
            "serviceType": "hdfs",
            "resultReason": "/spark2-history",
            "eventTime": "2017-06-20T00:44:14Z",
            "requestUser": "spark",
            "action": "write",
            "resourcePath": "/spark2-history/.2307a621-68de-4b21-a463-832294d00ec2",
            "resourceType": "path",
            "sequenceNumber": 1394645,
            "eventCount": 1,
            "eventDuration": 0
        },
        {
            "id": 863163027,
            "createDate": null,
            "updateDate": null,
            "auditType": 0,
            "accessResult": 1,
            "accessType": "WRITE",
            "aclEnforcer": "hadoop-acl",
            "clientIP": "172.16.16.151",
            "policyId": -1,
            "repoName": "cluster_hadoop",
            "repoType": 1,
            "serviceType": "hdfs",
            "resultReason": "/spark2-history",
            "eventTime": "2017-06-20T00:44:14Z",
            "requestUser": "spark",
            "action": "write",
            "resourcePath": "/spark2-history/.2307a621-68de-4b21-a463-832294d00ec2",
            "resourceType": "path",
            "sequenceNumber": 1394642,
            "eventCount": 1,
            "eventDuration": 0
        },
        {
            "id": 863163026,
            "createDate": null,
            "updateDate": null,
            "auditType": 0,
            "accessResult": 1,
            "accessType": "READ_EXECUTE",
            "aclEnforcer": "hadoop-acl",
            "clientIP": "172.16.16.151",
            "policyId": -1,
            "repoName": "cluster_hadoop",
            "repoType": 1,
            "serviceType": "hdfs",
            "resultReason": "/ats/active",
            "eventTime": "2017-06-20T00:44:07Z",
            "requestUser": "yarn",
            "action": "read",
            "resourcePath": "/ats/active",
            "resourceType": "path",
            "sequenceNumber": 1394640,
            "eventCount": 1,
            "eventDuration": 0
        },
        {
            "id": 863163024,
            "createDate": null,
            "updateDate": null,
            "auditType": 0,
            "accessResult": 1,
            "accessType": "READ",
            "aclEnforcer": "hadoop-acl",
            "clientIP": "172.16.16.151",
            "policyId": -1,
            "repoName": "cluster_hadoop",
            "repoType": 1,
            "serviceType": "hdfs",
            "resultReason": "/spark2-history/application_1496884763607_0003.inprogress",
            "eventTime": "2017-06-20T00:44:04Z",
            "requestUser": "spark",
            "action": "read",
            "resourcePath": "/spark2-history/application_1496884763607_0003.inprogress",
            "resourceType": "path",
            "sequenceNumber": 1394637,
            "eventCount": 1,
            "eventDuration": 0
        },
        {
            "id": 863163022,
            "createDate": null,
            "updateDate": null,
            "auditType": 0,
            "accessResult": 1,
            "accessType": "READ",
            "aclEnforcer": "hadoop-acl",
            "clientIP": "172.16.16.151",
            "policyId": -1,
            "repoName": "cluster_hadoop",
            "repoType": 1,
            "serviceType": "hdfs",
            "resultReason": "/spark2-history/application_1496884763607_0002.inprogress",
            "eventTime": "2017-06-20T00:44:04Z",
            "requestUser": "spark",
            "action": "read",
            "resourcePath": "/spark2-history/application_1496884763607_0002.inprogress",
            "resourceType": "path",
            "sequenceNumber": 1394633,
            "eventCount": 1,
            "eventDuration": 0
        },
        {
            "id": 863163023,
            "createDate": null,
            "updateDate": null,
            "auditType": 0,
            "accessResult": 1,
            "accessType": "READ",
            "aclEnforcer": "hadoop-acl",
            "clientIP": "172.16.16.151",
            "policyId": -1,
            "repoName": "cluster_hadoop",
            "repoType": 1,
            "serviceType": "hdfs",
            "resultReason": "/spark2-history/application_1496884763607_0004.inprogress",
            "eventTime": "2017-06-20T00:44:04Z",
            "requestUser": "spark",
            "action": "read",
            "resourcePath": "/spark2-history/application_1496884763607_0004.inprogress",
            "resourceType": "path",
            "sequenceNumber": 1394635,
            "eventCount": 1,
            "eventDuration": 0
        },
        {
            "id": 863163021,
            "createDate": null,
            "updateDate": null,
            "auditType": 0,
            "accessResult": 1,
            "accessType": "READ_EXECUTE",
            "aclEnforcer": "hadoop-acl",
            "clientIP": "172.16.16.151",
            "policyId": -1,
            "repoName": "cluster_hadoop",
            "repoType": 1,
            "serviceType": "hdfs",
            "resultReason": "/spark2-history",
            "eventTime": "2017-06-20T00:44:04Z",
            "requestUser": "spark",
            "action": "read",
            "resourcePath": "/spark2-history",
            "resourceType": "path",
            "sequenceNumber": 1394631,
            "eventCount": 1,
            "eventDuration": 0
        },
        {
            "id": 863163019,
            "createDate": null,
            "updateDate": null,
            "auditType": 0,
            "accessResult": 1,
            "accessType": "WRITE",
            "aclEnforcer": "hadoop-acl",
            "clientIP": "172.16.16.151",
            "policyId": -1,
            "repoName": "cluster_hadoop",
            "repoType": 1,
            "serviceType": "hdfs",
            "resultReason": "/spark2-history",
            "eventTime": "2017-06-20T00:44:04Z",
            "requestUser": "spark",
            "action": "write",
            "resourcePath": "/spark2-history/.555112af-0a1c-41ad-89e3-6f0c40c6d621",
            "resourceType": "path",
            "sequenceNumber": 1394628,
            "eventCount": 1,
            "eventDuration": 0
        },
        {
            "id": 863162996,
            "createDate": null,
            "updateDate": null,
            "auditType": 0,
            "accessResult": 1,
            "accessType": "WRITE",
            "aclEnforcer": "hadoop-acl",
            "clientIP": "172.16.16.151",
            "policyId": -1,
            "repoName": "cluster_hadoop",
            "repoType": 1,
            "serviceType": "hdfs",
            "resultReason": "/spark2-history",
            "eventTime": "2017-06-20T00:44:04Z",
            "requestUser": "spark",
            "action": "write",
            "resourcePath": "/spark2-history/.555112af-0a1c-41ad-89e3-6f0c40c6d621",
            "resourceType": "path",
            "sequenceNumber": 1394625,
            "eventCount": 1,
            "eventDuration": 0
        },
        {
            "id": 863162995,
            "createDate": null,
            "updateDate": null,
            "auditType": 0,
            "accessResult": 1,
            "accessType": "READ",
            "aclEnforcer": "hadoop-acl",
            "clientIP": "172.16.16.151",
            "policyId": -1,
            "repoName": "cluster_hadoop",
            "repoType": 1,
            "serviceType": "hdfs",
            "resultReason": "/spark2-history/application_1496884763607_0003.inprogress",
            "eventTime": "2017-06-20T00:43:54Z",
            "requestUser": "spark",
            "action": "read",
            "resourcePath": "/spark2-history/application_1496884763607_0003.inprogress",
            "resourceType": "path",
            "sequenceNumber": 1394623,
            "eventCount": 1,
            "eventDuration": 0
        },
        {
            "id": 863162993,
            "createDate": null,
            "updateDate": null,
            "auditType": 0,
            "accessResult": 1,
            "accessType": "READ",
            "aclEnforcer": "hadoop-acl",
            "clientIP": "172.16.16.151",
            "policyId": -1,
            "repoName": "cluster_hadoop",
            "repoType": 1,
            "serviceType": "hdfs",
            "resultReason": "/spark2-history/application_1496884763607_0002.inprogress",
            "eventTime": "2017-06-20T00:43:54Z",
            "requestUser": "spark",
            "action": "read",
            "resourcePath": "/spark2-history/application_1496884763607_0002.inprogress",
            "resourceType": "path",
            "sequenceNumber": 1394619,
            "eventCount": 1,
            "eventDuration": 0
        },
        {
            "id": 863162994,
            "createDate": null,
            "updateDate": null,
            "auditType": 0,
            "accessResult": 1,
            "accessType": "READ",
            "aclEnforcer": "hadoop-acl",
            "clientIP": "172.16.16.151",
            "policyId": -1,
            "repoName": "cluster_hadoop",
            "repoType": 1,
            "serviceType": "hdfs",
            "resultReason": "/spark2-history/application_1496884763607_0004.inprogress",
            "eventTime": "2017-06-20T00:43:54Z",
            "requestUser": "spark",
            "action": "read",
            "resourcePath": "/spark2-history/application_1496884763607_0004.inprogress",
            "resourceType": "path",
            "sequenceNumber": 1394621,
            "eventCount": 1,
            "eventDuration": 0
        },
        {
            "id": 863162992,
            "createDate": null,
            "updateDate": null,
            "auditType": 0,
            "accessResult": 1,
            "accessType": "READ_EXECUTE",
            "aclEnforcer": "hadoop-acl",
            "clientIP": "172.16.16.151",
            "policyId": -1,
            "repoName": "cluster_hadoop",
            "repoType": 1,
            "serviceType": "hdfs",
            "resultReason": "/spark2-history",
            "eventTime": "2017-06-20T00:43:54Z",
            "requestUser": "spark",
            "action": "read",
            "resourcePath": "/spark2-history",
            "resourceType": "path",
            "sequenceNumber": 1394617,
            "eventCount": 1,
            "eventDuration": 0
        },
        {
            "id": 863162990,
            "createDate": null,
            "updateDate": null,
            "auditType": 0,
            "accessResult": 1,
            "accessType": "WRITE",
            "aclEnforcer": "hadoop-acl",
            "clientIP": "172.16.16.151",
            "policyId": -1,
            "repoName": "cluster_hadoop",
            "repoType": 1,
            "serviceType": "hdfs",
            "resultReason": "/spark2-history",
            "eventTime": "2017-06-20T00:43:53Z",
            "requestUser": "spark",
            "action": "write",
            "resourcePath": "/spark2-history/.1beba8d8-1608-461a-944d-0fcdd2ee8561",
            "resourceType": "path",
            "sequenceNumber": 1394614,
            "eventCount": 1,
            "eventDuration": 0
        },
        {
            "id": 863162988,
            "createDate": null,
            "updateDate": null,
            "auditType": 0,
            "accessResult": 1,
            "accessType": "WRITE",
            "aclEnforcer": "hadoop-acl",
            "clientIP": "172.16.16.151",
            "policyId": -1,
            "repoName": "cluster_hadoop",
            "repoType": 1,
            "serviceType": "hdfs",
            "resultReason": "/spark2-history",
            "eventTime": "2017-06-20T00:43:53Z",
            "requestUser": "spark",
            "action": "write",
            "resourcePath": "/spark2-history/.1beba8d8-1608-461a-944d-0fcdd2ee8561",
            "resourceType": "path",
            "sequenceNumber": 1394611,
            "eventCount": 1,
            "eventDuration": 0
        },
        {
            "id": 863162966,
            "createDate": null,
            "updateDate": null,
            "auditType": 0,
            "accessResult": 1,
            "accessType": "READ_EXECUTE",
            "aclEnforcer": "hadoop-acl",
            "clientIP": "172.16.16.151",
            "policyId": -1,
            "repoName": "cluster_hadoop",
            "repoType": 1,
            "serviceType": "hdfs",
            "resultReason": "/ats/active",
            "eventTime": "2017-06-20T00:43:52Z",
            "requestUser": "yarn",
            "action": "read",
            "resourcePath": "/ats/active",
            "resourceType": "path",
            "sequenceNumber": 1394609,
            "eventCount": 1,
            "eventDuration": 0
        },
        {
            "id": 863162964,
            "createDate": null,
            "updateDate": null,
            "auditType": 0,
            "accessResult": 1,
            "accessType": "READ",
            "aclEnforcer": "hadoop-acl",
            "clientIP": "172.16.16.151",
            "policyId": -1,
            "repoName": "cluster_hadoop",
            "repoType": 1,
            "serviceType": "hdfs",
            "resultReason": "/spark2-history/application_1496884763607_0003.inprogress",
            "eventTime": "2017-06-20T00:43:43Z",
            "requestUser": "spark",
            "action": "read",
            "resourcePath": "/spark2-history/application_1496884763607_0003.inprogress",
            "resourceType": "path",
            "sequenceNumber": 1394606,
            "eventCount": 1,
            "eventDuration": 0
        },
        {
            "id": 863162962,
            "createDate": null,
            "updateDate": null,
            "auditType": 0,
            "accessResult": 1,
            "accessType": "READ",
            "aclEnforcer": "hadoop-acl",
            "clientIP": "172.16.16.151",
            "policyId": -1,
            "repoName": "cluster_hadoop",
            "repoType": 1,
            "serviceType": "hdfs",
            "resultReason": "/spark2-history/application_1496884763607_0002.inprogress",
            "eventTime": "2017-06-20T00:43:43Z",
            "requestUser": "spark",
            "action": "read",
            "resourcePath": "/spark2-history/application_1496884763607_0002.inprogress",
            "resourceType": "path",
            "sequenceNumber": 1394602,
            "eventCount": 1,
            "eventDuration": 0
        },
        {
            "id": 863162963,
            "createDate": null,
            "updateDate": null,
            "auditType": 0,
            "accessResult": 1,
            "accessType": "READ",
            "aclEnforcer": "hadoop-acl",
            "clientIP": "172.16.16.151",
            "policyId": -1,
            "repoName": "cluster_hadoop",
            "repoType": 1,
            "serviceType": "hdfs",
            "resultReason": "/spark2-history/application_1496884763607_0004.inprogress",
            "eventTime": "2017-06-20T00:43:43Z",
            "requestUser": "spark",
            "action": "read",
            "resourcePath": "/spark2-history/application_1496884763607_0004.inprogress",
            "resourceType": "path",
            "sequenceNumber": 1394604,
            "eventCount": 1,
            "eventDuration": 0
        },
        {
            "id": 863162961,
            "createDate": null,
            "updateDate": null,
            "auditType": 0,
            "accessResult": 1,
            "accessType": "READ_EXECUTE",
            "aclEnforcer": "hadoop-acl",
            "clientIP": "172.16.16.151",
            "policyId": -1,
            "repoName": "cluster_hadoop",
            "repoType": 1,
            "serviceType": "hdfs",
            "resultReason": "/spark2-history",
            "eventTime": "2017-06-20T00:43:43Z",
            "requestUser": "spark",
            "action": "read",
            "resourcePath": "/spark2-history",
            "resourceType": "path",
            "sequenceNumber": 1394600,
            "eventCount": 1,
            "eventDuration": 0
        },
        {
            "id": 863162959,
            "createDate": null,
            "updateDate": null,
            "auditType": 0,
            "accessResult": 1,
            "accessType": "WRITE",
            "aclEnforcer": "hadoop-acl",
            "clientIP": "172.16.16.151",
            "policyId": -1,
            "repoName": "cluster_hadoop",
            "repoType": 1,
            "serviceType": "hdfs",
            "resultReason": "/spark2-history",
            "eventTime": "2017-06-20T00:43:43Z",
            "requestUser": "spark",
            "action": "write",
            "resourcePath": "/spark2-history/.18d63a06-d9f8-4187-90b1-38177d1f5008",
            "resourceType": "path",
            "sequenceNumber": 1394597,
            "eventCount": 1,
            "eventDuration": 0
        },
        {
            "id": 863163055,
            "createDate": null,
            "updateDate": null,
            "auditType": 0,
            "accessResult": 1,
            "accessType": "READ",
            "aclEnforcer": "hadoop-acl",
            "clientIP": "172.16.16.151",
            "policyId": -1,
            "repoName": "cluster_hadoop",
            "repoType": 1,
            "serviceType": "hdfs",
            "resultReason": "/spark2-history/application_1496884763607_0003.inprogress",
            "eventTime": "2017-06-20T00:44:14Z",
            "requestUser": "spark",
            "action": "read",
            "resourcePath": "/spark2-history/application_1496884763607_0003.inprogress",
            "resourceType": "path",
            "sequenceNumber": 1394654,
            "eventCount": 1,
            "eventDuration": 0
        },
        {
            "id": 863163053,
            "createDate": null,
            "updateDate": null,
            "auditType": 0,
            "accessResult": 1,
            "accessType": "READ",
            "aclEnforcer": "hadoop-acl",
            "clientIP": "172.16.16.151",
            "policyId": -1,
            "repoName": "cluster_hadoop",
            "repoType": 1,
            "serviceType": "hdfs",
            "resultReason": "/spark2-history/application_1496884763607_0002.inprogress",
            "eventTime": "2017-06-20T00:44:14Z",
            "requestUser": "spark",
            "action": "read",
            "resourcePath": "/spark2-history/application_1496884763607_0002.inprogress",
            "resourceType": "path",
            "sequenceNumber": 1394650,
            "eventCount": 1,
            "eventDuration": 0
        },
        {
            "id": 863163054,
            "createDate": null,
            "updateDate": null,
            "auditType": 0,
            "accessResult": 1,
            "accessType": "READ",
            "aclEnforcer": "hadoop-acl",
            "clientIP": "172.16.16.151",
            "policyId": -1,
            "repoName": "cluster_hadoop",
            "repoType": 1,
            "serviceType": "hdfs",
            "resultReason": "/spark2-history/application_1496884763607_0004.inprogress",
            "eventTime": "2017-06-20T00:44:14Z",
            "requestUser": "spark",
            "action": "read",
            "resourcePath": "/spark2-history/application_1496884763607_0004.inprogress",
            "resourceType": "path",
            "sequenceNumber": 1394652,
            "eventCount": 1,
            "eventDuration": 0
        },
        {
            "id": 863163052,
            "createDate": null,
            "updateDate": null,
            "auditType": 0,
            "accessResult": 1,
            "accessType": "READ_EXECUTE",
            "aclEnforcer": "hadoop-acl",
            "clientIP": "172.16.16.151",
            "policyId": -1,
            "repoName": "cluster_hadoop",
            "repoType": 1,
            "serviceType": "hdfs",
            "resultReason": "/spark2-history",
            "eventTime": "2017-06-20T00:44:14Z",
            "requestUser": "spark",
            "action": "read",
            "resourcePath": "/spark2-history",
            "resourceType": "path",
            "sequenceNumber": 1394648,
            "eventCount": 1,
            "eventDuration": 0
        },
        {
            "id": 863163050,
            "createDate": null,
            "updateDate": null,
            "auditType": 0,
            "accessResult": 1,
            "accessType": "WRITE",
            "aclEnforcer": "hadoop-acl",
            "clientIP": "172.16.16.151",
            "policyId": -1,
            "repoName": "cluster_hadoop",
            "repoType": 1,
            "serviceType": "hdfs",
            "resultReason": "/spark2-history",
            "eventTime": "2017-06-20T00:44:14Z",
            "requestUser": "spark",
            "action": "write",
            "resourcePath": "/spark2-history/.2307a621-68de-4b21-a463-832294d00ec2",
            "resourceType": "path",
            "sequenceNumber": 1394645,
            "eventCount": 1,
            "eventDuration": 0
        },
        {
            "id": 863163027,
            "createDate": null,
            "updateDate": null,
            "auditType": 0,
            "accessResult": 1,
            "accessType": "WRITE",
            "aclEnforcer": "hadoop-acl",
            "clientIP": "172.16.16.151",
            "policyId": -1,
            "repoName": "cluster_hadoop",
            "repoType": 1,
            "serviceType": "hdfs",
            "resultReason": "/spark2-history",
            "eventTime": "2017-06-20T00:44:14Z",
            "requestUser": "spark",
            "action": "write",
            "resourcePath": "/spark2-history/.2307a621-68de-4b21-a463-832294d00ec2",
            "resourceType": "path",
            "sequenceNumber": 1394642,
            "eventCount": 1,
            "eventDuration": 0
        },
        {
            "id": 863163026,
            "createDate": null,
            "updateDate": null,
            "auditType": 0,
            "accessResult": 1,
            "accessType": "READ_EXECUTE",
            "aclEnforcer": "hadoop-acl",
            "clientIP": "172.16.16.151",
            "policyId": -1,
            "repoName": "cluster_hadoop",
            "repoType": 1,
            "serviceType": "hdfs",
            "resultReason": "/ats/active",
            "eventTime": "2017-06-20T00:44:07Z",
            "requestUser": "yarn",
            "action": "read",
            "resourcePath": "/ats/active",
            "resourceType": "path",
            "sequenceNumber": 1394640,
            "eventCount": 1,
            "eventDuration": 0
        },
        {
            "id": 863163024,
            "createDate": null,
            "updateDate": null,
            "auditType": 0,
            "accessResult": 1,
            "accessType": "READ",
            "aclEnforcer": "hadoop-acl",
            "clientIP": "172.16.16.151",
            "policyId": -1,
            "repoName": "cluster_hadoop",
            "repoType": 1,
            "serviceType": "hdfs",
            "resultReason": "/spark2-history/application_1496884763607_0003.inprogress",
            "eventTime": "2017-06-20T00:44:04Z",
            "requestUser": "spark",
            "action": "read",
            "resourcePath": "/spark2-history/application_1496884763607_0003.inprogress",
            "resourceType": "path",
            "sequenceNumber": 1394637,
            "eventCount": 1,
            "eventDuration": 0
        },
        {
            "id": 863163022,
            "createDate": null,
            "updateDate": null,
            "auditType": 0,
            "accessResult": 1,
            "accessType": "READ",
            "aclEnforcer": "hadoop-acl",
            "clientIP": "172.16.16.151",
            "policyId": -1,
            "repoName": "cluster_hadoop",
            "repoType": 1,
            "serviceType": "hdfs",
            "resultReason": "/spark2-history/application_1496884763607_0002.inprogress",
            "eventTime": "2017-06-20T00:44:04Z",
            "requestUser": "spark",
            "action": "read",
            "resourcePath": "/spark2-history/application_1496884763607_0002.inprogress",
            "resourceType": "path",
            "sequenceNumber": 1394633,
            "eventCount": 1,
            "eventDuration": 0
        },
        {
            "id": 863163023,
            "createDate": null,
            "updateDate": null,
            "auditType": 0,
            "accessResult": 1,
            "accessType": "READ",
            "aclEnforcer": "hadoop-acl",
            "clientIP": "172.16.16.151",
            "policyId": -1,
            "repoName": "cluster_hadoop",
            "repoType": 1,
            "serviceType": "hdfs",
            "resultReason": "/spark2-history/application_1496884763607_0004.inprogress",
            "eventTime": "2017-06-20T00:44:04Z",
            "requestUser": "spark",
            "action": "read",
            "resourcePath": "/spark2-history/application_1496884763607_0004.inprogress",
            "resourceType": "path",
            "sequenceNumber": 1394635,
            "eventCount": 1,
            "eventDuration": 0
        },
        {
            "id": 863163021,
            "createDate": null,
            "updateDate": null,
            "auditType": 0,
            "accessResult": 1,
            "accessType": "READ_EXECUTE",
            "aclEnforcer": "hadoop-acl",
            "clientIP": "172.16.16.151",
            "policyId": -1,
            "repoName": "cluster_hadoop",
            "repoType": 1,
            "serviceType": "hdfs",
            "resultReason": "/spark2-history",
            "eventTime": "2017-06-20T00:44:04Z",
            "requestUser": "spark",
            "action": "read",
            "resourcePath": "/spark2-history",
            "resourceType": "path",
            "sequenceNumber": 1394631,
            "eventCount": 1,
            "eventDuration": 0
        },
        {
            "id": 863163019,
            "createDate": null,
            "updateDate": null,
            "auditType": 0,
            "accessResult": 1,
            "accessType": "WRITE",
            "aclEnforcer": "hadoop-acl",
            "clientIP": "172.16.16.151",
            "policyId": -1,
            "repoName": "cluster_hadoop",
            "repoType": 1,
            "serviceType": "hdfs",
            "resultReason": "/spark2-history",
            "eventTime": "2017-06-20T00:44:04Z",
            "requestUser": "spark",
            "action": "write",
            "resourcePath": "/spark2-history/.555112af-0a1c-41ad-89e3-6f0c40c6d621",
            "resourceType": "path",
            "sequenceNumber": 1394628,
            "eventCount": 1,
            "eventDuration": 0
        },
        {
            "id": 863162996,
            "createDate": null,
            "updateDate": null,
            "auditType": 0,
            "accessResult": 1,
            "accessType": "WRITE",
            "aclEnforcer": "hadoop-acl",
            "clientIP": "172.16.16.151",
            "policyId": -1,
            "repoName": "cluster_hadoop",
            "repoType": 1,
            "serviceType": "hdfs",
            "resultReason": "/spark2-history",
            "eventTime": "2017-06-20T00:44:04Z",
            "requestUser": "spark",
            "action": "write",
            "resourcePath": "/spark2-history/.555112af-0a1c-41ad-89e3-6f0c40c6d621",
            "resourceType": "path",
            "sequenceNumber": 1394625,
            "eventCount": 1,
            "eventDuration": 0
        },
        {
            "id": 863162995,
            "createDate": null,
            "updateDate": null,
            "auditType": 0,
            "accessResult": 1,
            "accessType": "READ",
            "aclEnforcer": "hadoop-acl",
            "clientIP": "172.16.16.151",
            "policyId": -1,
            "repoName": "cluster_hadoop",
            "repoType": 1,
            "serviceType": "hdfs",
            "resultReason": "/spark2-history/application_1496884763607_0003.inprogress",
            "eventTime": "2017-06-20T00:43:54Z",
            "requestUser": "spark",
            "action": "read",
            "resourcePath": "/spark2-history/application_1496884763607_0003.inprogress",
            "resourceType": "path",
            "sequenceNumber": 1394623,
            "eventCount": 1,
            "eventDuration": 0
        },
        {
            "id": 863162993,
            "createDate": null,
            "updateDate": null,
            "auditType": 0,
            "accessResult": 1,
            "accessType": "READ",
            "aclEnforcer": "hadoop-acl",
            "clientIP": "172.16.16.151",
            "policyId": -1,
            "repoName": "cluster_hadoop",
            "repoType": 1,
            "serviceType": "hdfs",
            "resultReason": "/spark2-history/application_1496884763607_0002.inprogress",
            "eventTime": "2017-06-20T00:43:54Z",
            "requestUser": "spark",
            "action": "read",
            "resourcePath": "/spark2-history/application_1496884763607_0002.inprogress",
            "resourceType": "path",
            "sequenceNumber": 1394619,
            "eventCount": 1,
            "eventDuration": 0
        },
        {
            "id": 863162994,
            "createDate": null,
            "updateDate": null,
            "auditType": 0,
            "accessResult": 1,
            "accessType": "READ",
            "aclEnforcer": "hadoop-acl",
            "clientIP": "172.16.16.151",
            "policyId": -1,
            "repoName": "cluster_hadoop",
            "repoType": 1,
            "serviceType": "hdfs",
            "resultReason": "/spark2-history/application_1496884763607_0004.inprogress",
            "eventTime": "2017-06-20T00:43:54Z",
            "requestUser": "spark",
            "action": "read",
            "resourcePath": "/spark2-history/application_1496884763607_0004.inprogress",
            "resourceType": "path",
            "sequenceNumber": 1394621,
            "eventCount": 1,
            "eventDuration": 0
        },
        {
            "id": 863162992,
            "createDate": null,
            "updateDate": null,
            "auditType": 0,
            "accessResult": 1,
            "accessType": "READ_EXECUTE",
            "aclEnforcer": "hadoop-acl",
            "clientIP": "172.16.16.151",
            "policyId": -1,
            "repoName": "cluster_hadoop",
            "repoType": 1,
            "serviceType": "hdfs",
            "resultReason": "/spark2-history",
            "eventTime": "2017-06-20T00:43:54Z",
            "requestUser": "spark",
            "action": "read",
            "resourcePath": "/spark2-history",
            "resourceType": "path",
            "sequenceNumber": 1394617,
            "eventCount": 1,
            "eventDuration": 0
        },
        {
            "id": 863162990,
            "createDate": null,
            "updateDate": null,
            "auditType": 0,
            "accessResult": 1,
            "accessType": "WRITE",
            "aclEnforcer": "hadoop-acl",
            "clientIP": "172.16.16.151",
            "policyId": -1,
            "repoName": "cluster_hadoop",
            "repoType": 1,
            "serviceType": "hdfs",
            "resultReason": "/spark2-history",
            "eventTime": "2017-06-20T00:43:53Z",
            "requestUser": "spark",
            "action": "write",
            "resourcePath": "/spark2-history/.1beba8d8-1608-461a-944d-0fcdd2ee8561",
            "resourceType": "path",
            "sequenceNumber": 1394614,
            "eventCount": 1,
            "eventDuration": 0
        },
        {
            "id": 863162988,
            "createDate": null,
            "updateDate": null,
            "auditType": 0,
            "accessResult": 1,
            "accessType": "WRITE",
            "aclEnforcer": "hadoop-acl",
            "clientIP": "172.16.16.151",
            "policyId": -1,
            "repoName": "cluster_hadoop",
            "repoType": 1,
            "serviceType": "hdfs",
            "resultReason": "/spark2-history",
            "eventTime": "2017-06-20T00:43:53Z",
            "requestUser": "spark",
            "action": "write",
            "resourcePath": "/spark2-history/.1beba8d8-1608-461a-944d-0fcdd2ee8561",
            "resourceType": "path",
            "sequenceNumber": 1394611,
            "eventCount": 1,
            "eventDuration": 0
        },
        {
            "id": 863162966,
            "createDate": null,
            "updateDate": null,
            "auditType": 0,
            "accessResult": 1,
            "accessType": "READ_EXECUTE",
            "aclEnforcer": "hadoop-acl",
            "clientIP": "172.16.16.151",
            "policyId": -1,
            "repoName": "cluster_hadoop",
            "repoType": 1,
            "serviceType": "hdfs",
            "resultReason": "/ats/active",
            "eventTime": "2017-06-20T00:43:52Z",
            "requestUser": "yarn",
            "action": "read",
            "resourcePath": "/ats/active",
            "resourceType": "path",
            "sequenceNumber": 1394609,
            "eventCount": 1,
            "eventDuration": 0
        },
        {
            "id": 863162964,
            "createDate": null,
            "updateDate": null,
            "auditType": 0,
            "accessResult": 1,
            "accessType": "READ",
            "aclEnforcer": "hadoop-acl",
            "clientIP": "172.16.16.151",
            "policyId": -1,
            "repoName": "cluster_hadoop",
            "repoType": 1,
            "serviceType": "hdfs",
            "resultReason": "/spark2-history/application_1496884763607_0003.inprogress",
            "eventTime": "2017-06-20T00:43:43Z",
            "requestUser": "spark",
            "action": "read",
            "resourcePath": "/spark2-history/application_1496884763607_0003.inprogress",
            "resourceType": "path",
            "sequenceNumber": 1394606,
            "eventCount": 1,
            "eventDuration": 0
        },
        {
            "id": 863162962,
            "createDate": null,
            "updateDate": null,
            "auditType": 0,
            "accessResult": 1,
            "accessType": "READ",
            "aclEnforcer": "hadoop-acl",
            "clientIP": "172.16.16.151",
            "policyId": -1,
            "repoName": "cluster_hadoop",
            "repoType": 1,
            "serviceType": "hdfs",
            "resultReason": "/spark2-history/application_1496884763607_0002.inprogress",
            "eventTime": "2017-06-20T00:43:43Z",
            "requestUser": "spark",
            "action": "read",
            "resourcePath": "/spark2-history/application_1496884763607_0002.inprogress",
            "resourceType": "path",
            "sequenceNumber": 1394602,
            "eventCount": 1,
            "eventDuration": 0
        },
        {
            "id": 863162963,
            "createDate": null,
            "updateDate": null,
            "auditType": 0,
            "accessResult": 1,
            "accessType": "READ",
            "aclEnforcer": "hadoop-acl",
            "clientIP": "172.16.16.151",
            "policyId": -1,
            "repoName": "cluster_hadoop",
            "repoType": 1,
            "serviceType": "hdfs",
            "resultReason": "/spark2-history/application_1496884763607_0004.inprogress",
            "eventTime": "2017-06-20T00:43:43Z",
            "requestUser": "spark",
            "action": "read",
            "resourcePath": "/spark2-history/application_1496884763607_0004.inprogress",
            "resourceType": "path",
            "sequenceNumber": 1394604,
            "eventCount": 1,
            "eventDuration": 0
        },
        {
            "id": 863162961,
            "createDate": null,
            "updateDate": null,
            "auditType": 0,
            "accessResult": 1,
            "accessType": "READ_EXECUTE",
            "aclEnforcer": "hadoop-acl",
            "clientIP": "172.16.16.151",
            "policyId": -1,
            "repoName": "cluster_hadoop",
            "repoType": 1,
            "serviceType": "hdfs",
            "resultReason": "/spark2-history",
            "eventTime": "2017-06-20T00:43:43Z",
            "requestUser": "spark",
            "action": "read",
            "resourcePath": "/spark2-history",
            "resourceType": "path",
            "sequenceNumber": 1394600,
            "eventCount": 1,
            "eventDuration": 0
        },
        {
            "id": 863162959,
            "createDate": null,
            "updateDate": null,
            "auditType": 0,
            "accessResult": 1,
            "accessType": "WRITE",
            "aclEnforcer": "hadoop-acl",
            "clientIP": "172.16.16.151",
            "policyId": -1,
            "repoName": "cluster_hadoop",
            "repoType": 1,
            "serviceType": "hdfs",
            "resultReason": "/spark2-history",
            "eventTime": "2017-06-20T00:43:43Z",
            "requestUser": "spark",
            "action": "write",
            "resourcePath": "/spark2-history/.18d63a06-d9f8-4187-90b1-38177d1f5008",
            "resourceType": "path",
            "sequenceNumber": 1394597,
            "eventCount": 1,
            "eventDuration": 0
        }
    ]
}
app.controller('accessTableController', ['$scope', '$http', '$state', '$translate', function($scope, $http, $state, $translate) {

    $scope.formData = {};
    $scope.tableloading = true;
    $scope.pageSize = 25;
    $scope.page = 0;
    $scope.pageFirst = true;
    $scope.searchPageFirst = true;
    $scope.accessListResponse = {};
    $scope.searchAdminListResponse = {};

    /* 翻页回调函数 */
    $scope.pageSelectCallback = function(page_index, jq) {
        $scope.page = page_index;
        $scope.startIndex = $scope.page * $scope.pageSize;
        $scope.getAccessListInfo($scope.page, $scope.pageSize, $scope.startIndex,
            $scope.getAccessListSuccess,$scope.getAccessListError);
        return false;
    };


    /* 获取用户组列表信息成功后的回调函数 */
    $scope.getAccessListSuccess = function (vXAccessResponse) {

        var vXAccessAudits = vXAccessResponse.vXAccessAudits;
        /*var vXAccessAudits = vxAccessJson.vXAccessAudits;*/
        $scope.accessListResponse = vXAccessResponse;

        for (var i = 0; i < vXAccessAudits.length; i++) {
            if (vXAccessAudits[i]["eventTime"] != null) {
                vXAccessAudits[i]["eventTime"] = new Date(vXAccessAudits[i]["eventTime"]).toLocaleString();
            }
        }
        $scope.accessTable = vXAccessAudits;
        $scope.tableLength = $scope.accessTable.length;
        $scope.tableloading = false;

        if ($scope.pageFirst == true) {
            $scope.pageFirst = false;
            $('#page').pagination(vXAccessResponse.totalCount, {
                num_edge_entries: 1,
                callback: $scope.pageSelectCallback,
                items_per_page : $scope.pageSize
            });
        }

        $scope.$digest();
    };

    $scope.getAccessListError = function (vXAccessResponse) {
        bootbox.alert("Get Access List Information Error!!!");
    };

    /* 搜索翻页回调函数 */
    $scope.searchPageSelectCallback = function(page_index, jq) {
        $scope.page = page_index;
        $scope.startIndex = $scope.page * $scope.pageSize;
        var total_page = Math.ceil($scope.searchAdminListResponse.totalCount/$scope.pageSize);
        var urlString = "service/assets/accessAudit?page" + $scope.page +
            "&pageSize=" + $scope.pageSize +
            "&total_pages=" + total_page +
            "&startIndex=" + $scope.startIndex +
            "&sortBy=eventTime" + "&repoName=" + $scope.formData.repoName;
        ajaxGet(urlString, $scope.getServiceNameSuccess, $scope.getServiceNameError);
        return false;
    };

    $scope.getServiceNameSuccess = function (vXAccessResponse) {
        var vXAccessAudits = vXAccessResponse.vXAccessAudits;
        $scope.searchAdminListResponse = vXAccessResponse;
        for (var i = 0; i < vXAccessAudits.length; i++) {
            for (var i = 0; i < vXAccessAudits.length; i++) {
                if (vXAccessAudits[i]["eventTime"] != null) {
                    vXAccessAudits[i]["eventTime"] = new Date(vXAccessAudits[i]["eventTime"]).toLocaleString();
                }
            }
        }

        $scope.accessTable = vXAccessAudits;
        $scope.tableLength = $scope.accessTable.length;
        $scope.tableloading = false;

        if ($scope.searchPageFirst == true) {
            $scope.searchPageFirst= false;
            $('#page').pagination(vXAccessResponse.totalCount, {
                num_edge_entries: 1,
                callback: $scope.searchPageSelectCallback,
                items_per_page : $scope.pageSize
            });
        }

        $scope.$digest();
    };

    $scope.getServiceNameError = function (vXAccessResponse) {
        bootbox.alert("No service name: " + $scope.formData.repoName + " to be found!");
    };

    /* 响应搜索框输入完成后，按下enter按键后的响应函数 */
    document.searchAccessByServiceName = function(e) {
        var total_page=0;
        $scope.searchPageFirst = true;
        $scope.pageFirst = true;
        if (!e) {
            e = window.event;
        }
        if ((e.keyCode || e.which) == 13) {
            var urlString;
            if (accessTransform($scope.formData.repoName)=== 0) {
                $scope.getAccessListInfo(0,$scope.pageSize,0,$scope.getAccessListSuccess, $scope.getAccessListError);
            }

            urlString = "service/assets/accessAudit?page=0" +
                "&pageSize=" + $scope.pageSize +
                "&startIndex=0" + "&sortBy=eventTime" + "&repoName=" + $scope.formData.repoName;
            ajaxGet(urlString, $scope.getServiceNameSuccess, $scope.getServiceNameError);
        }
    }

    /* 获取用户组列表信息公共接口函数定义 */
    $scope.getAccessListInfo = function (page, pageSize, startIndex, successCallback, errorCallback) {
        ajaxGet("service/assets/accessAudit?page="+page+"&pageSize="+pageSize+"&startIndex="+ startIndex +
            "&sortBy=eventTime", successCallback, errorCallback);
    }

    /* 获取用户组列表信息 */
    $scope.getAccessListInfo(0,$scope.pageSize,0,$scope.getAccessListSuccess, $scope.getAccessListError);
}
]);
